### ISSUE TITLE
got nothing but a black screen on my iPhone 5s??

### ISSUE THREAD

**Issue by young40** [FlexMonkey/ParticleLab#11]

**Comment by FlexMonkey** [comment]
Hi,

Unfortunately, I don't have access to a iPhone 5s, but since it uses an A7, Metal should work.

I've added a new function to the delegate protocol, particleLabMetalUnavailable(), which is invoked if your device doesn't support Metal. Also, I've changed the constructor so that you can try to create a system with less particles, maybe try ParticleCount.OneMillion

Finally, Metal doesn't work in the simulator, just in case you're trying :)

Simon

**Comment by young40** [comment]
Hi Simon,

I have update the codes, but still not work.

**Comment by FlexMonkey** [comment]
Without a 5s myself, I'm a bit stuck.

I've just added a small change to the setUpMetal() method - is device nil on your 5s, if so, the delegate's particleLabMetalUnavailable() should be invoked and it implies your phone doesn't support Metal.  Is step() being fired? Are you seeing a trace of the frame rate in your console? Can you run other Metal based code on your phone? 

I've also added another enum to ParticleCount for half a million particles, maybe try that in the ParticleLab constructor?

Simon

**Comment by young40** [comment]
device is not nil and step() is fired.

I download Epic Zen Garden from App Store, It working fine. it's Metal based, am I right?

BTW, I'm using iOS 8.3 & Xcode 6.3.

**Comment by FlexMonkey** [comment]
Ok, I wonder if the view's frame hasn't been properly constructed in viewDidLoad() - can you print the dimensions of the ParticleLab instance to the console to make sure its width and height aren't zero?

Did you try a smaller number of particles?

Simon

---

+44 (0) 7973 669691
sgladman@gmail.com
http://flexmonkey.blogspot.com/

**Comment by FlexMonkey** [comment]
Hi,

Just to say it's not just you, other 5s users experience the same. As I mentioned before, sadly I don't have access to a 5s, so I'll live in hope some kind soul can fix it for me :)

---

+44 (0) 7973 669691
sgladman@gmail.com
http://flexmonkey.blogspot.com/

**Comment by FlexMonkey** [comment]
Yep - this looks like a 5s issue. I'll try to borrow one, but until I can actually get my hands on a 5s, I'm a bit stuck. Sorry about that :(

**Comment by young40** [comment]
thank you!

**Comment by sketch34** [comment]
I also get black screen on iPhone5s, but I noticed that if you change the present code to below I do see particles stuck to the bottom and right edges of the screen:

```
        commandEncoder.endEncoding()
        commandBuffer.presentDrawable(drawable)
        commandBuffer.commit()
```

The particles don't move though they are just lined up along the edge of the screen, the simulation doesn't appear to be running at all.

**Comment by FlexMonkey** [comment]
Yep - if you look at other comments on this project, performance on pre-A8 devices is pretty ropey in comparison. I don't have a 5s to test on, so I'd venture to say this project is for iPhone 6 / iPad Air 2 and above.
