### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by scheung38** [FlexMonkey/ParticleLab#25]
Not sure exactly how to resolve this after Clean Success but Build returns:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang", line 62, in <module>
    stderr=subprocess.PIPE)
  File "/Users/sebc/anaconda/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/Users/sebc/anaconda/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 35] Resource temporarily unavailable
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code

**Comment by FlexMonkey** [comment]
Hi,

You're not targeting the simulator or a pre A7 device are you?

Simon

**Comment by scheung38** [comment]
This is for my iPhone 6 Plus device

**Comment by scheung38** [comment]
Hi Simon,

Is this audio visualization? Just that it is visualizing by itself when there is no audio microphone or music been played? Or have I missed something?

**Comment by FlexMonkey** [comment]
Depends which branch. The master branch isn't audio visualisation, but the AudioKit one is.

Do you have the build working now?

Simon

**Comment by scheung38** [comment]
ok got the audio visualization branch, but how would you 
1. measure average audio dB
2. time 
3. capture a snapshot

from start to stop when, say a button is pressed?

**Comment by FlexMonkey** [comment]
Some of these questions are outside the scope of this project and you probably want to aim them at Stackoverflow or AudioKit. 

By capture a snapshot, do you mean a video snapshot of the particles or a snapshot of the audio?

If you have the build working now, I'll close this issue. Cheers.
