### ISSUE TITLE
Launching this on my 6s gives me a SIGABRT

### ISSUE THREAD

**Issue by Sam0711er** [FlexMonkey/ParticleLab#28]
Launching gives me the following SIGABRT: 
_/BuildRoot/Library/Caches/com.apple.xbs/Sources/Metal/Metal-55.1.1/ToolsLayers/Debug/MTLDebugComputeCommandEncoder.mm:654: failed assertion `Function writes texture (outTexture[0]) whos usage (0x05) doesn't specify MTLTextureUsageShaderWrite (0x02)'
(lldb)_

Xcode marks this line (Line 315 in ParticleLab.swift):
_commandEncoder.dispatchThreadgroups(threadgroupsPerGrid, threadsPerThreadgroup: threadsPerThreadgroup)_

**Comment by FlexMonkey** [comment]
This is a real pain and seems to have been introduced in the most recent Xcode 7.1. I've raised a Radar with Apple.

**The workaround is to edit the scheme for the project and under "options" set "Metal API Validation" to disabled, then everything should work fine.**

This setting doesn't appear to register properly with Xcode's source control, hence I haven't been able to update the project properly. 

This is the same fix if you're targeting tvOS or OS X.

Cheers!
