### ISSUE TITLE
please update to swift 3.0

### ISSUE THREAD

**Issue by JaDenis** [FlexMonkey/ParticleLab#34]
![2016-10-11 22 32 31](https://cloud.githubusercontent.com/assets/17880706/19285486/bdb5d5dc-9002-11e6-9eca-2f887a97f830.png)
I feel it's not that hard to fix, but can't come up with anything :(

**Comment by FlexMonkey** [comment]
I'm crazy busy at the moment and will try to update these repos over the coming months. Filterpedia is my first priority then ParticleLab. Cheers!

**Comment by JaDenis** [comment]
Thank you so much, for your efforts!

2016-10-12 9:44 GMT+03:00 simon gladman notifications@github.com:
