### ISSUE TITLE
Trying to open project in Xcode 7.3.1

### ISSUE THREAD

**Issue by hollowaytyl** [FlexMonkey/ParticleLab#35]
Xcode keeps telling that there's "no module import MetalKit". All I'm doing is opening the project straight from Git. Do I need a Podfile or something? Thanks!

**Comment by FlexMonkey** [comment]
Hi. There are no podfiles or external dependencies. MetalKit can't target a simulator - try targeting an actual device and it should work fine.

**Comment by hollowaytyl** [comment]
Perfect! Thank you and great work on this. Just one quick question - is there any way to change the background of the particles instead of just the view background? For example, could I achieve
making the particles move on a red background if the view background is red? 

Basically, is there a way to make the black "box" not be there and instead just show particles floating? I'm looking for a native look type thing. I love your project! Thanks again.
 
![img_7831](https://cloud.githubusercontent.com/assets/16567066/21579119/0446c458-cf6d-11e6-9618-7b9bd1dcae2d.PNG)

**Comment by FlexMonkey** [comment]
This line: 
```
blankBitmapRawData = [UInt8](count: Int(imageWidth * imageHeight * 4), repeatedValue: 0)
```
Creates at array which clears the background with zeros. If you create an array which represents `red`, you should get a red background.
