### ISSUE TITLE
Please update for latest Xcode + Swift + iOS 10

### ISSUE THREAD

**Issue by MKGitHub** [FlexMonkey/ParticleLab#37]
Please update for latest Xcode + Swift + iOS 10

**Comment by kent-white** [comment]
https://github.com/FlexMonkey/ParticleLab/issues/36

**Comment by FlexMonkey** [comment]
Hi,

Unfortunately, the terms of my contract with my new employer prohibits me from working on this code at the moment. You should find that the Swift 3 migrator handles the majority of issues.

Sorry I can't help further at this time.

Simon
